name: 'OPRF Asset Updater'
description: 'A workflow which automatically updates OPRF standard asset files from the OpRedFlag repository'
author: BobDotCom
branding:
  icon: box
  color: gray-dark
inputs:
  repository:
    description: 'Location of OpRedFlag asset GitHub repository, in User/Repo format'
    required: false
    default: 'NikolaiVChr/OpRedFlag'
  repository-branch:
    description: 'The branch of the OpRedFlag repository to use'
    required: false
    default: 'master'
  version-file:
    description: 'Location of local versions.json file'
    required: false
    default: "oprf-versions.json"
  include:
    description: 'Asset keys to update, separated by commas. Default: "*"'
    required: false
    default: "*"
  exclude:
    description: 'Asset keys to skip, separated by commas. Default: ""'
    required: false
    default: ""
  major:
    description: 'Allow major updates, not recommended until after verifying compatibility'
    required: false
    default: "false"
  strict:
    description: "Fail if local file versions are newer than remote"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: "Install requirements"
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt
    - shell: bash
      run: echo "Update OPRF Assets" >> ${{ github.action_path }}/commit.txt
    - name: "Update assets"
      env:
        PYTHONUNBUFFERED: "1"
      shell: bash
      run: python ${{ github.action_path }}/main.py -r "${{ inputs.repository }}" -b "${{ inputs.repository-branch }}" -v "${{ inputs.version-file }}" -i "${{ inputs.include }}" -e "${{ inputs.exclude }}" -m "${{ inputs.major }}" -s "${{ inputs.strict }}" >> ${{ github.action_path }}/commit.txt
    - name: Set commit message
      id: commit-message-step
      shell: bash
      run: |
        echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
        cat ${{ github.action_path }}/commit.txt >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: "${{ github.event_name == 'workflow_dispatch' }}"
      with:
        commit_message: ${{ steps.commit-message-step.outputs.commit_message }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: "${{ github.event_name != 'workflow_dispatch' }}"
      with:
        commit_message: ${{ steps.commit-message-step.outputs.commit_message }}
        commit_author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
