name: 'OPRF Asset Updater'
description: 'A workflow which automatically updates OPRF standard asset files from the OpRedFlag repository'
inputs:
  repository:
    description: 'Location of OpRedFlag asset GitHub repository, in User/Repo format'
    required: false
    default: 'BobDotCom/OpRedFlag'
  repository-branch:
    description: 'The branch of the repository to use'
    required: false
    default: 'master'
  version-file:
    description: 'Location of local versions.json file'
    required: false
    default: "oprf-versions.json"
  include:
    description: 'Files to update, separated by commas. Default: "*"'
    required: false
    default: "*"
  exclude:
    description: 'Files to skip, separated by commas. Default: ""'
    required: false
    default: ""
  major:
    description: 'Allow major updates, not recommended until after verifying compatibility'
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: "Install requirements"
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt
    - name: "Update assets"
      id: update-assets
      env:
        PYTHONUNBUFFERED: "1"
      shell: bash
      uses: mathiasvr/command-output@v2
      with:
        run: ${{ github.action_path }}/main.py -r "${{ inputs.repository }}" -b "${{ inputs.repository-branch }}" -v "${{ inputs.version-file }}" -i "${{ inputs.include }}" -e "${{ inputs.exclude }}" -m "${{ inputs.major }}"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update OPRF Assets\n\n${{ steps.update-assets.outputs.stdout }}
